/**
 * PR-comment Markdown renderer for {@link VerdictResponse}.
 *
 * Output hovers near ~40 lines, plain ASCII only (no emoji) per the repo's
 * terminal-friendly conventions. The renderer is pure — it takes a
 * VerdictResponse and produces a string — so tests can pin byte-for-byte
 * output.
 */

import type { VerdictResponse } from "./verdict-types.js";

const TIER_HEADER: Record<VerdictResponse["verdict"], string> = {
  auto_merge: "AUTO-MERGE",
  single_review: "SINGLE REVIEW",
  dual_review: "DUAL REVIEW",
  expert_review: "EXPERT REVIEW",
  block: "BLOCK",
};

const SEVERITY_PREFIX: Record<"info" | "warn" | "error", string> = {
  info: "(i)",
  warn: "(!)",
  error: "[!!]",
};

export function renderVerdictMarkdown(v: VerdictResponse): string {
  const lines: string[] = [];
  lines.push(`## OpenCodeHub Verdict: \`${v.verdict}\` — ${TIER_HEADER[v.verdict]}`);
  lines.push("");
  lines.push(`**Confidence:** ${(v.confidence * 100).toFixed(0)}% | **Exit code:** ${v.exitCode}`);
  lines.push(
    `**${v.changedFileCount}** files changed | **${v.affectedSymbolCount}** symbols affected | **${v.communitiesTouched.length}** communities touched`,
  );
  lines.push(`**Blast radius:** ${v.blastRadius}`);
  lines.push("");

  lines.push("### Reasoning");
  if (v.reasoningChain.length === 0) {
    lines.push("- (no signals — empty diff or no graph coverage)");
  } else {
    for (const s of v.reasoningChain) {
      lines.push(`- ${SEVERITY_PREFIX[s.severity]} **${s.label}**: ${String(s.value)}`);
    }
  }
  lines.push("");

  lines.push("### Recommended reviewers");
  if (v.recommendedReviewers.length === 0) {
    lines.push("- (none — ownership phase has not run, or no OWNED_BY edges found)");
  } else {
    for (const r of v.recommendedReviewers) {
      const identity = r.email.length > 0 ? r.email : `sha256:${r.emailHash.slice(0, 10)}...`;
      const display = r.name.length > 0 ? r.name : "unknown";
      lines.push(`- ${display} <${identity}> (weight=${r.weight.toFixed(3)})`);
    }
  }
  lines.push("");

  lines.push("### Labels");
  lines.push(
    v.githubLabels.length === 0 ? "- (none)" : v.githubLabels.map((l) => `\`${l}\``).join(" "),
  );
  lines.push("");

  if (v.decisionBoundary.nextTier !== null) {
    lines.push(
      `### Decision boundary — ${v.decisionBoundary.distancePercent.toFixed(0)}% to \`${v.decisionBoundary.nextTier}\``,
    );
    lines.push("Narrow the diff to reduce blast radius, or add test coverage to de-escalate.");
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "*Generated by [OpenCodeHub](https://github.com/opencodehub/opencodehub) — `codehub verdict`.*",
  );
  return lines.join("\n");
}
