/**
 * GENERATED characterization golden — DO NOT hand-edit.
 *
 * This file is the committed, byte-stable snapshot consumed by
 * `characterization.test.ts`. It is a compiled-in `const` (not a JSON asset
 * read at runtime) so the test resolves it from `dist` with a plain import,
 * dodging `import.meta.url` path-offset fragility on bundle collapse.
 *
 * Each entry maps a `LanguageId` to the `canonicalJson(...)` string of that
 * language's SORTED extractor output (see the test for the sort key), one
 * string per core extractor. Full-value equality against these strings is the
 * safety net for the extractor-generic refactor: any drift in a hash-relevant
 * field (calleeOwner / qualifiedName / startLine / owner / …) changes the
 * canonical string and fails the test with a per-language, per-extractor diff.
 *
 * To regenerate (ONLY for a deliberate, reviewed behavior change):
 *   UPDATE_CHARACTERIZATION=1 pnpm --filter @opencodehub/ingestion build
 *   UPDATE_CHARACTERIZATION=1 pnpm --filter @opencodehub/ingestion test
 * The test rewrites THIS file's `GOLDEN` literal, then re-asserts against it.
 */

import type { LanguageId } from "@opencodehub/core-types";

/** Per-extractor canonical-JSON snapshots for one language. */
export interface ExtractorSnapshot {
  readonly definitions: string;
  readonly calls: string;
  readonly heritage: string;
  readonly imports: string;
}

// biome-ignore format: generated literal — leave the regenerator's formatting intact.
export const GOLDEN: Record<LanguageId, ExtractorSnapshot> = {
  "typescript": {
    "definitions": "[{\"endLine\":15,\"filePath\":\"greeter.ts\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.greet\",\"startLine\":12},{\"endLine\":18,\"filePath\":\"greeter.ts\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.log\",\"startLine\":16},{\"endLine\":19,\"filePath\":\"greeter.ts\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Welcomer\",\"qualifiedName\":\"Welcomer\",\"startLine\":10},{\"endLine\":21,\"filePath\":\"greeter.ts\",\"isConst\":true,\"isExported\":true,\"kind\":\"Const\",\"name\":\"MESSAGE\",\"qualifiedName\":\"MESSAGE\",\"startLine\":21},{\"endLine\":24,\"filePath\":\"greeter.ts\",\"isConst\":true,\"isExported\":true,\"kind\":\"Const\",\"name\":\"w\",\"owner\":\"run\",\"qualifiedName\":\"run.w\",\"startLine\":24},{\"endLine\":26,\"filePath\":\"greeter.ts\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":23},{\"endLine\":8,\"filePath\":\"greeter.ts\",\"isExported\":true,\"kind\":\"Interface\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":6}]",
    "calls": "[{\"calleeName\":\"debug\",\"calleeOwner\":\"Logger\",\"callerQualifiedName\":\"Welcomer.log\",\"filePath\":\"greeter.ts\",\"startLine\":17},{\"calleeName\":\"greet\",\"calleeOwner\":\"w\",\"callerQualifiedName\":\"run\",\"filePath\":\"greeter.ts\",\"startLine\":25},{\"calleeName\":\"log\",\"calleeOwner\":\"this\",\"callerQualifiedName\":\"Welcomer.greet\",\"filePath\":\"greeter.ts\",\"startLine\":13}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"greeter.ts\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":6},{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"greeter.ts\",\"parentName\":\"Greeter\",\"relation\":\"IMPLEMENTS\",\"startLine\":10}]",
    "imports": "[{\"filePath\":\"greeter.ts\",\"importedNames\":[\"Logger\"],\"kind\":\"named\",\"source\":\"./logger.js\"},{\"filePath\":\"greeter.ts\",\"importedNames\":[\"other\"],\"kind\":\"named\",\"source\":\"./mixed\"},{\"filePath\":\"greeter.ts\",\"isWildcard\":true,\"kind\":\"namespace\",\"localAlias\":\"util\",\"source\":\"./util\"},{\"filePath\":\"greeter.ts\",\"kind\":\"default\",\"localAlias\":\"defaultExport\",\"source\":\"./mixed\"}]"
  },
  "tsx": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"page.tsx\",\"isConst\":true,\"isExported\":true,\"kind\":\"Const\",\"name\":\"label\",\"owner\":\"Greeting\",\"qualifiedName\":\"Greeting.label\",\"startLine\":10},{\"endLine\":12,\"filePath\":\"page.tsx\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"Greeting\",\"qualifiedName\":\"Greeting\",\"startLine\":9},{\"endLine\":17,\"filePath\":\"page.tsx\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"render\",\"owner\":\"Page\",\"qualifiedName\":\"Page.render\",\"startLine\":15},{\"endLine\":18,\"filePath\":\"page.tsx\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Page\",\"qualifiedName\":\"Page\",\"startLine\":14},{\"endLine\":7,\"filePath\":\"page.tsx\",\"isExported\":false,\"kind\":\"Interface\",\"name\":\"Props\",\"qualifiedName\":\"Props\",\"startLine\":5}]",
    "calls": "[{\"calleeName\":\"format\",\"calleeOwner\":\"svc\",\"callerQualifiedName\":\"Greeting\",\"filePath\":\"page.tsx\",\"startLine\":10}]",
    "heritage": "[{\"childQualifiedName\":\"Page\",\"filePath\":\"page.tsx\",\"parentName\":\"React.Component\",\"relation\":\"EXTENDS\",\"startLine\":14}]",
    "imports": "[{\"filePath\":\"page.tsx\",\"importedNames\":[\"Button\"],\"kind\":\"named\",\"source\":\"./button.js\"},{\"filePath\":\"page.tsx\",\"kind\":\"default\",\"localAlias\":\"React\",\"source\":\"react\"}]"
  },
  "javascript": {
    "definitions": "[{\"endLine\":16,\"filePath\":\"esm.js\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.greet\",\"startLine\":12},{\"endLine\":17,\"filePath\":\"esm.js\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":11},{\"endLine\":20,\"filePath\":\"esm.js\",\"isConst\":true,\"isExported\":true,\"kind\":\"Const\",\"name\":\"g\",\"owner\":\"run\",\"qualifiedName\":\"run.g\",\"startLine\":20},{\"endLine\":22,\"filePath\":\"esm.js\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":19},{\"endLine\":26,\"filePath\":\"esm.js\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"_internalHelper\",\"qualifiedName\":\"_internalHelper\",\"startLine\":24},{\"endLine\":8,\"filePath\":\"esm.js\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":6},{\"endLine\":9,\"filePath\":\"esm.js\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":5}]",
    "calls": "[{\"calleeName\":\"debug\",\"calleeOwner\":\"Logger\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"esm.js\",\"startLine\":14},{\"calleeName\":\"greet\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"esm.js\",\"startLine\":21},{\"calleeName\":\"hello\",\"calleeOwner\":\"this\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"esm.js\",\"startLine\":13}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"esm.js\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":11}]",
    "imports": "[{\"filePath\":\"esm.js\",\"importedNames\":[\"Logger\"],\"kind\":\"named\",\"source\":\"./logger.js\"},{\"filePath\":\"esm.js\",\"kind\":\"default\",\"localAlias\":\"defaultExport\",\"source\":\"./default.js\"}]"
  },
  "python": {
    "definitions": "[{\"endLine\":12,\"filePath\":\"mod.py\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":10},{\"endLine\":12,\"filePath\":\"mod.py\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Base\",\"qualifiedName\":\"Base.greet\",\"startLine\":11},{\"endLine\":17,\"filePath\":\"mod.py\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.greet\",\"startLine\":15},{\"endLine\":20,\"filePath\":\"mod.py\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"_private\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter._private\",\"startLine\":19},{\"endLine\":20,\"filePath\":\"mod.py\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":14},{\"endLine\":23,\"filePath\":\"mod.py\",\"isExported\":true,\"kind\":\"Variable\",\"name\":\"g\",\"owner\":\"run\",\"qualifiedName\":\"run.g\",\"startLine\":23},{\"endLine\":24,\"filePath\":\"mod.py\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":22},{\"endLine\":7,\"filePath\":\"mod.py\",\"isConst\":true,\"isExported\":true,\"kind\":\"Const\",\"name\":\"MAX_RETRY\",\"qualifiedName\":\"MAX_RETRY\",\"startLine\":7},{\"endLine\":8,\"filePath\":\"mod.py\",\"isConst\":false,\"isExported\":false,\"kind\":\"Const\",\"name\":\"_internal_version\",\"qualifiedName\":\"_internal_version\",\"startLine\":8}]",
    "calls": "[{\"calleeName\":\"Greeter\",\"callerQualifiedName\":\"run\",\"filePath\":\"mod.py\",\"startLine\":23},{\"calleeName\":\"getenv\",\"calleeOwner\":\"os\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"mod.py\",\"startLine\":16},{\"calleeName\":\"greet\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"mod.py\",\"startLine\":24},{\"calleeName\":\"greet\",\"calleeOwner\":\"self\",\"callerQualifiedName\":\"Greeter._private\",\"filePath\":\"mod.py\",\"startLine\":20},{\"calleeName\":\"super\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"mod.py\",\"startLine\":17},{\"calleeName\":\"super\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"mod.py\",\"startLine\":17}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"mod.py\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":14},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"mod.py\",\"parentName\":\"Mixin\",\"relation\":\"EXTENDS\",\"startLine\":14}]",
    "imports": "[{\"filePath\":\"mod.py\",\"importedNames\":[\"List\",\"Opt\"],\"kind\":\"named\",\"source\":\"typing\"},{\"filePath\":\"mod.py\",\"isWildcard\":true,\"kind\":\"package-wildcard\",\"source\":\"utils\"},{\"filePath\":\"mod.py\",\"kind\":\"namespace\",\"localAlias\":\"np\",\"source\":\"numpy\"},{\"filePath\":\"mod.py\",\"kind\":\"namespace\",\"source\":\"os\"}]"
  },
  "go": {
    "definitions": "[{\"endLine\":1,\"filePath\":\"greet.go\",\"isExported\":false,\"kind\":\"Module\",\"name\":\"greet\",\"qualifiedName\":\"greet\",\"startLine\":1},{\"endLine\":11,\"filePath\":\"greet.go\",\"isExported\":true,\"kind\":\"Struct\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":9},{\"endLine\":15,\"filePath\":\"greet.go\",\"isExported\":true,\"kind\":\"Interface\",\"name\":\"Speaker\",\"qualifiedName\":\"Speaker\",\"startLine\":13},{\"endLine\":19,\"filePath\":\"greet.go\",\"isExported\":true,\"kind\":\"Const\",\"name\":\"MaxGreet\",\"qualifiedName\":\"MaxGreet\",\"startLine\":17},{\"endLine\":23,\"filePath\":\"greet.go\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"Greet\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.Greet\",\"startLine\":21},{\"endLine\":28,\"filePath\":\"greet.go\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":25},{\"endLine\":30,\"filePath\":\"greet.go\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"Exported\",\"qualifiedName\":\"Exported\",\"startLine\":30},{\"endLine\":31,\"filePath\":\"greet.go\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"internal\",\"qualifiedName\":\"internal\",\"startLine\":31}]",
    "calls": "[{\"calleeName\":\"Greet\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"greet.go\",\"startLine\":27},{\"calleeName\":\"Sprintf\",\"calleeOwner\":\"fmt\",\"callerQualifiedName\":\"Greeter.Greet\",\"filePath\":\"greet.go\",\"startLine\":22},{\"calleeName\":\"ToLower\",\"calleeOwner\":\"str\",\"callerQualifiedName\":\"Greeter.Greet\",\"filePath\":\"greet.go\",\"startLine\":22}]",
    "heritage": "[]",
    "imports": "[{\"filePath\":\"greet.go\",\"kind\":\"package-wildcard\",\"localAlias\":\".\",\"source\":\"errors\"},{\"filePath\":\"greet.go\",\"kind\":\"package-wildcard\",\"localAlias\":\"str\",\"source\":\"strings\"},{\"filePath\":\"greet.go\",\"kind\":\"package-wildcard\",\"source\":\"fmt\"}]"
  },
  "rust": {
    "definitions": "[{\"endLine\":13,\"filePath\":\"lib.rs\",\"isExported\":true,\"kind\":\"Struct\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":11},{\"endLine\":19,\"filePath\":\"lib.rs\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.greet\",\"startLine\":16},{\"endLine\":25,\"filePath\":\"lib.rs\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.log\",\"startLine\":23},{\"endLine\":28,\"filePath\":\"lib.rs\",\"isExported\":true,\"kind\":\"Const\",\"name\":\"DEFAULT\",\"qualifiedName\":\"DEFAULT\",\"startLine\":28},{\"endLine\":30,\"filePath\":\"lib.rs\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"internal\",\"qualifiedName\":\"internal\",\"startLine\":30},{\"endLine\":34,\"filePath\":\"lib.rs\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":31},{\"endLine\":9,\"filePath\":\"lib.rs\",\"isExported\":true,\"kind\":\"Trait\",\"name\":\"Greet\",\"qualifiedName\":\"Greet\",\"startLine\":7}]",
    "calls": "[{\"calleeName\":\"debug\",\"calleeOwner\":\"Logger\",\"callerQualifiedName\":\"Greeter.log\",\"filePath\":\"lib.rs\",\"startLine\":24},{\"calleeName\":\"greet\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"lib.rs\",\"startLine\":33},{\"calleeName\":\"log\",\"calleeOwner\":\"self\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"lib.rs\",\"startLine\":17},{\"calleeName\":\"to_string\",\"calleeOwner\":\"\\\"world\\\"\",\"callerQualifiedName\":\"run\",\"filePath\":\"lib.rs\",\"startLine\":32}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"lib.rs\",\"parentName\":\"Greet\",\"relation\":\"IMPLEMENTS\",\"startLine\":15}]",
    "imports": "[{\"filePath\":\"lib.rs\",\"importedNames\":[\"HashMap\",\"Sorted\"],\"kind\":\"named\",\"source\":\"std::collections\"},{\"filePath\":\"lib.rs\",\"importedNames\":[\"Logger\"],\"kind\":\"named\",\"source\":\"crate::logger\"},{\"filePath\":\"lib.rs\",\"isWildcard\":true,\"kind\":\"package-wildcard\",\"source\":\"crate::util\"},{\"filePath\":\"lib.rs\",\"isWildcard\":true,\"kind\":\"package-wildcard\",\"source\":\"self::public_api\"}]"
  },
  "java": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"Welcomer.java\",\"isExported\":true,\"kind\":\"Interface\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":8},{\"endLine\":14,\"filePath\":\"Welcomer.java\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":12},{\"endLine\":21,\"filePath\":\"Welcomer.java\",\"isExported\":true,\"kind\":\"Constructor\",\"name\":\"Welcomer\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.Welcomer\",\"startLine\":19},{\"endLine\":25,\"filePath\":\"Welcomer.java\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.greet\",\"startLine\":23},{\"endLine\":30,\"filePath\":\"Welcomer.java\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"run\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.run\",\"startLine\":27},{\"endLine\":31,\"filePath\":\"Welcomer.java\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Welcomer\",\"qualifiedName\":\"Welcomer\",\"startLine\":16},{\"endLine\":33,\"filePath\":\"Welcomer.java\",\"isExported\":false,\"kind\":\"Class\",\"name\":\"Internal\",\"qualifiedName\":\"Internal\",\"startLine\":33},{\"endLine\":9,\"filePath\":\"Welcomer.java\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.greet\",\"startLine\":9}]",
    "calls": "[{\"calleeName\":\"greet\",\"callerQualifiedName\":\"Welcomer.run\",\"filePath\":\"Welcomer.java\",\"startLine\":28},{\"calleeName\":\"greet\",\"callerQualifiedName\":\"Welcomer.run\",\"filePath\":\"Welcomer.java\",\"startLine\":29},{\"calleeName\":\"println\",\"calleeOwner\":\"System.out\",\"callerQualifiedName\":\"Welcomer.run\",\"filePath\":\"Welcomer.java\",\"startLine\":29}]",
    "heritage": "[{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"Welcomer.java\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":16},{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"Welcomer.java\",\"parentName\":\"Greeter\",\"relation\":\"IMPLEMENTS\",\"startLine\":16},{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"Welcomer.java\",\"parentName\":\"Runnable\",\"relation\":\"IMPLEMENTS\",\"startLine\":16}]",
    "imports": "[{\"filePath\":\"Welcomer.java\",\"importedNames\":[\"List\"],\"kind\":\"named\",\"source\":\"java.util\"},{\"filePath\":\"Welcomer.java\",\"importedNames\":[\"PI\"],\"kind\":\"named\",\"source\":\"java.lang.Math\"},{\"filePath\":\"Welcomer.java\",\"isWildcard\":true,\"kind\":\"package-wildcard\",\"source\":\"java.util.concurrent\"}]"
  },
  "csharp": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"Welcomer.cs\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"Greet\",\"owner\":\"IGreeter\",\"qualifiedName\":\"IGreeter.Greet\",\"startLine\":10},{\"endLine\":11,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Interface\",\"name\":\"IGreeter\",\"qualifiedName\":\"IGreeter\",\"startLine\":8},{\"endLine\":16,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":13},{\"endLine\":25,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Constructor\",\"name\":\"Welcomer\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.Welcomer\",\"startLine\":22},{\"endLine\":30,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"Greet\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.Greet\",\"startLine\":27},{\"endLine\":35,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"Dispose\",\"owner\":\"Welcomer\",\"qualifiedName\":\"Welcomer.Dispose\",\"startLine\":32},{\"endLine\":36,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Welcomer\",\"qualifiedName\":\"Welcomer\",\"startLine\":18},{\"endLine\":38,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Record\",\"name\":\"Pair\",\"qualifiedName\":\"Pair\",\"startLine\":38},{\"endLine\":40,\"filePath\":\"Welcomer.cs\",\"isExported\":true,\"kind\":\"Struct\",\"name\":\"Point\",\"qualifiedName\":\"Point\",\"startLine\":40},{\"endLine\":42,\"filePath\":\"Welcomer.cs\",\"isExported\":false,\"kind\":\"Class\",\"name\":\"Hidden\",\"qualifiedName\":\"Hidden\",\"startLine\":42},{\"endLine\":43,\"filePath\":\"Welcomer.cs\",\"isExported\":false,\"kind\":\"Namespace\",\"name\":\"App.Greet\",\"qualifiedName\":\"App.Greet\",\"startLine\":6}]",
    "calls": "[{\"calleeName\":\"WriteLine\",\"calleeOwner\":\"Console\",\"callerQualifiedName\":\"Welcomer.Dispose\",\"filePath\":\"Welcomer.cs\",\"startLine\":34}]",
    "heritage": "[{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"Welcomer.cs\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":18},{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"Welcomer.cs\",\"parentName\":\"IDisposable\",\"relation\":\"IMPLEMENTS\",\"startLine\":18},{\"childQualifiedName\":\"Welcomer\",\"filePath\":\"Welcomer.cs\",\"parentName\":\"IGreeter\",\"relation\":\"IMPLEMENTS\",\"startLine\":18}]",
    "imports": "[{\"filePath\":\"Welcomer.cs\",\"kind\":\"namespace\",\"localAlias\":\"Json\",\"source\":\"Newtonsoft.Json\"},{\"filePath\":\"Welcomer.cs\",\"kind\":\"namespace\",\"source\":\"System\"},{\"filePath\":\"Welcomer.cs\",\"kind\":\"namespace\",\"source\":\"System.Collections.Generic\"}]"
  },
  "c": {
    "definitions": "[{\"endLine\":13,\"filePath\":\"user.c\",\"isExported\":true,\"kind\":\"Enum\",\"name\":\"Status\",\"owner\":\"Status\",\"qualifiedName\":\"Status.Status\",\"startLine\":10},{\"endLine\":13,\"filePath\":\"user.c\",\"isExported\":true,\"kind\":\"Typedef\",\"name\":\"Status\",\"qualifiedName\":\"Status\",\"startLine\":10},{\"endLine\":19,\"filePath\":\"user.c\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"reset_counter\",\"qualifiedName\":\"reset_counter\",\"startLine\":17},{\"endLine\":26,\"filePath\":\"user.c\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"register_user\",\"qualifiedName\":\"register_user\",\"startLine\":21},{\"endLine\":32,\"filePath\":\"user.c\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"main\",\"qualifiedName\":\"main\",\"startLine\":28},{\"endLine\":8,\"filePath\":\"user.c\",\"isExported\":true,\"kind\":\"Struct\",\"name\":\"User\",\"owner\":\"User\",\"qualifiedName\":\"User.User\",\"startLine\":5},{\"endLine\":8,\"filePath\":\"user.c\",\"isExported\":true,\"kind\":\"Typedef\",\"name\":\"User\",\"qualifiedName\":\"User\",\"startLine\":5}]",
    "calls": "[{\"calleeName\":\"printf\",\"callerQualifiedName\":\"register_user\",\"filePath\":\"user.c\",\"startLine\":24},{\"calleeName\":\"register_user\",\"callerQualifiedName\":\"main\",\"filePath\":\"user.c\",\"startLine\":29},{\"calleeName\":\"reset_counter\",\"callerQualifiedName\":\"main\",\"filePath\":\"user.c\",\"startLine\":30}]",
    "heritage": "[]",
    "imports": "[{\"filePath\":\"user.c\",\"kind\":\"package-wildcard\",\"source\":\"stdio.h\"},{\"filePath\":\"user.c\",\"kind\":\"package-wildcard\",\"source\":\"user.h\"}]"
  },
  "cpp": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":7},{\"endLine\":14,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"mix\",\"owner\":\"Mixin\",\"qualifiedName\":\"Mixin.mix\",\"startLine\":14},{\"endLine\":15,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Mixin\",\"qualifiedName\":\"Mixin\",\"startLine\":12},{\"endLine\":19,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"Greeter\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.Greeter\",\"startLine\":19},{\"endLine\":20,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.hello\",\"startLine\":20},{\"endLine\":23,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":17},{\"endLine\":31,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":25},{\"endLine\":33,\"filePath\":\"greet.cpp\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"_internalHelper\",\"qualifiedName\":\"_internalHelper\",\"startLine\":33},{\"endLine\":35,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Namespace\",\"name\":\"auth\",\"qualifiedName\":\"auth\",\"startLine\":5},{\"endLine\":9,\"filePath\":\"greet.cpp\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":9}]",
    "calls": "[{\"calleeName\":\"hello\",\"calleeOwner\":\"Base\",\"callerQualifiedName\":\"run\",\"filePath\":\"greet.cpp\",\"startLine\":30},{\"calleeName\":\"hello\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"greet.cpp\",\"startLine\":27},{\"calleeName\":\"hello\",\"calleeOwner\":\"ptr\",\"callerQualifiedName\":\"run\",\"filePath\":\"greet.cpp\",\"startLine\":29}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"greet.cpp\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":17},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"greet.cpp\",\"parentName\":\"Mixin\",\"relation\":\"EXTENDS\",\"startLine\":17}]",
    "imports": "[{\"filePath\":\"greet.cpp\",\"kind\":\"package-wildcard\",\"source\":\"db.h\"},{\"filePath\":\"greet.cpp\",\"kind\":\"package-wildcard\",\"source\":\"string\"}]"
  },
  "ruby": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":6},{\"endLine\":13,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"log\",\"qualifiedName\":\"log\",\"startLine\":13},{\"endLine\":14,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Module\",\"name\":\"Logger\",\"qualifiedName\":\"Logger\",\"startLine\":12},{\"endLine\":22,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.greet\",\"startLine\":19},{\"endLine\":26,\"filePath\":\"auth.rb\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"_private\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter._private\",\"startLine\":24},{\"endLine\":27,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":16},{\"endLine\":28,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Module\",\"name\":\"Auth\",\"qualifiedName\":\"Auth\",\"startLine\":5},{\"endLine\":33,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":30},{\"endLine\":9,\"filePath\":\"auth.rb\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"greet\",\"owner\":\"Base\",\"qualifiedName\":\"Base.greet\",\"startLine\":7}]",
    "calls": "[{\"calleeName\":\"greet\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"auth.rb\",\"startLine\":32},{\"calleeName\":\"greet\",\"callerQualifiedName\":\"Greeter._private\",\"filePath\":\"auth.rb\",\"startLine\":25},{\"calleeName\":\"log\",\"callerQualifiedName\":\"Greeter.greet\",\"filePath\":\"auth.rb\",\"startLine\":20},{\"calleeName\":\"new\",\"calleeOwner\":\"Auth::Greeter\",\"callerQualifiedName\":\"run\",\"filePath\":\"auth.rb\",\"startLine\":31}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"auth.rb\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":16},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"auth.rb\",\"parentName\":\"Logger\",\"relation\":\"IMPLEMENTS\",\"startLine\":17}]",
    "imports": "[{\"filePath\":\"auth.rb\",\"kind\":\"named\",\"source\":\"./session\"},{\"filePath\":\"auth.rb\",\"kind\":\"package-wildcard\",\"source\":\"digest\"}]"
  },
  "kotlin": {
    "definitions": "[{\"endLine\":12,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":12},{\"endLine\":13,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":11},{\"endLine\":19,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.hello\",\"startLine\":16},{\"endLine\":23,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.log\",\"startLine\":21},{\"endLine\":24,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":15},{\"endLine\":27,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Property\",\"name\":\"g\",\"owner\":\"run\",\"qualifiedName\":\"run.g\",\"startLine\":27},{\"endLine\":29,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":26},{\"endLine\":31,\"filePath\":\"Auth.kt\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"_privateHelper\",\"qualifiedName\":\"_privateHelper\",\"startLine\":31},{\"endLine\":8,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Logger\",\"qualifiedName\":\"Logger.log\",\"startLine\":8},{\"endLine\":9,\"filePath\":\"Auth.kt\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Logger\",\"qualifiedName\":\"Logger\",\"startLine\":7}]",
    "calls": "[{\"calleeName\":\"Greeter\",\"callerQualifiedName\":\"run\",\"filePath\":\"Auth.kt\",\"startLine\":27},{\"calleeName\":\"hello\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"Auth.kt\",\"startLine\":28},{\"calleeName\":\"hello\",\"calleeOwner\":\"super\",\"callerQualifiedName\":\"Greeter.hello\",\"filePath\":\"Auth.kt\",\"startLine\":18},{\"calleeName\":\"log\",\"callerQualifiedName\":\"Greeter.hello\",\"filePath\":\"Auth.kt\",\"startLine\":17},{\"calleeName\":\"println\",\"callerQualifiedName\":\"Greeter.log\",\"filePath\":\"Auth.kt\",\"startLine\":22}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.kt\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":15},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.kt\",\"parentName\":\"Logger\",\"relation\":\"EXTENDS\",\"startLine\":15}]",
    "imports": "[{\"filePath\":\"Auth.kt\",\"isWildcard\":true,\"kind\":\"package-wildcard\",\"source\":\"kotlin.collections\"},{\"filePath\":\"Auth.kt\",\"kind\":\"named\",\"source\":\"java.util.UUID\"}]"
  },
  "swift": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":8},{\"endLine\":22,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.hello\",\"startLine\":19},{\"endLine\":26,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.log\",\"startLine\":24},{\"endLine\":27,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":12},{\"endLine\":32,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":29},{\"endLine\":34,\"filePath\":\"Auth.swift\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"_privateHelper\",\"qualifiedName\":\"_privateHelper\",\"startLine\":34},{\"endLine\":6,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Interface\",\"name\":\"Logger\",\"qualifiedName\":\"Logger\",\"startLine\":4},{\"endLine\":9,\"filePath\":\"Auth.swift\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":9}]",
    "calls": "[{\"calleeName\":\"Greeter\",\"callerQualifiedName\":\"run\",\"filePath\":\"Auth.swift\",\"startLine\":30},{\"calleeName\":\"hello\",\"calleeOwner\":\"g\",\"callerQualifiedName\":\"run\",\"filePath\":\"Auth.swift\",\"startLine\":31},{\"calleeName\":\"hello\",\"calleeOwner\":\"super\",\"callerQualifiedName\":\"Greeter.hello\",\"filePath\":\"Auth.swift\",\"startLine\":21},{\"calleeName\":\"log\",\"callerQualifiedName\":\"Greeter.hello\",\"filePath\":\"Auth.swift\",\"startLine\":20},{\"calleeName\":\"print\",\"callerQualifiedName\":\"Greeter.log\",\"filePath\":\"Auth.swift\",\"startLine\":25}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.swift\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":12},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.swift\",\"parentName\":\"Logger\",\"relation\":\"EXTENDS\",\"startLine\":12}]",
    "imports": "[{\"filePath\":\"Auth.swift\",\"kind\":\"named\",\"source\":\"Foundation\"}]"
  },
  "php": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Interface\",\"name\":\"Authenticatable\",\"qualifiedName\":\"Authenticatable\",\"startLine\":7},{\"endLine\":14,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"touch\",\"owner\":\"Timestamps\",\"qualifiedName\":\"Timestamps.touch\",\"startLine\":14},{\"endLine\":15,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Trait\",\"name\":\"Timestamps\",\"qualifiedName\":\"Timestamps\",\"startLine\":12},{\"endLine\":19,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":19},{\"endLine\":2,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Namespace\",\"name\":\"Auth\",\"qualifiedName\":\"Auth\",\"startLine\":2},{\"endLine\":20,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":17},{\"endLine\":31,\"filePath\":\"Auth.php\",\"isExported\":false,\"kind\":\"Method\",\"name\":\"__construct\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.__construct\",\"startLine\":28},{\"endLine\":38,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"login\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.login\",\"startLine\":33},{\"endLine\":39,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":22},{\"endLine\":45,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":41},{\"endLine\":9,\"filePath\":\"Auth.php\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"login\",\"owner\":\"Authenticatable\",\"qualifiedName\":\"Authenticatable.login\",\"startLine\":9}]",
    "calls": "[{\"calleeName\":\"hello\",\"calleeOwner\":\"$this\",\"callerQualifiedName\":\"Greeter.login\",\"filePath\":\"Auth.php\",\"startLine\":35},{\"calleeName\":\"hello\",\"calleeOwner\":\"Base\",\"callerQualifiedName\":\"Greeter.login\",\"filePath\":\"Auth.php\",\"startLine\":36},{\"calleeName\":\"login\",\"calleeOwner\":\"$g\",\"callerQualifiedName\":\"run\",\"filePath\":\"Auth.php\",\"startLine\":44}]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.php\",\"parentName\":\"Authenticatable\",\"relation\":\"IMPLEMENTS\",\"startLine\":22},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.php\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":22},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"Auth.php\",\"parentName\":\"Timestamps\",\"relation\":\"IMPLEMENTS\",\"startLine\":24}]",
    "imports": "[{\"filePath\":\"Auth.php\",\"kind\":\"named\",\"source\":\"Psr/Log/LoggerInterface\"},{\"filePath\":\"Auth.php\",\"kind\":\"named\",\"source\":\"Timestamps\"},{\"filePath\":\"Auth.php\",\"kind\":\"package-wildcard\",\"source\":\"config.php\"}]"
  },
  "dart": {
    "definitions": "[{\"endLine\":10,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"touch\",\"qualifiedName\":\"touch\",\"startLine\":10},{\"endLine\":10,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"touch\",\"qualifiedName\":\"touch\",\"startLine\":10},{\"endLine\":11,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Trait\",\"name\":\"Timestamps\",\"qualifiedName\":\"Timestamps\",\"startLine\":9},{\"endLine\":14,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":14},{\"endLine\":14,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Base\",\"qualifiedName\":\"Base.hello\",\"startLine\":14},{\"endLine\":15,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Base\",\"qualifiedName\":\"Base\",\"startLine\":13},{\"endLine\":23,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.hello\",\"startLine\":23},{\"endLine\":23,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"hello\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.hello\",\"startLine\":23},{\"endLine\":29,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.log\",\"startLine\":29},{\"endLine\":29,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Greeter\",\"qualifiedName\":\"Greeter.log\",\"startLine\":29},{\"endLine\":32,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Greeter\",\"qualifiedName\":\"Greeter\",\"startLine\":17},{\"endLine\":34,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Function\",\"name\":\"run\",\"qualifiedName\":\"run\",\"startLine\":34},{\"endLine\":39,\"filePath\":\"auth.dart\",\"isExported\":false,\"kind\":\"Function\",\"name\":\"_privateHelper\",\"qualifiedName\":\"_privateHelper\",\"startLine\":39},{\"endLine\":6,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Method\",\"name\":\"log\",\"owner\":\"Logger\",\"qualifiedName\":\"Logger.log\",\"startLine\":6},{\"endLine\":7,\"filePath\":\"auth.dart\",\"isExported\":true,\"kind\":\"Class\",\"name\":\"Logger\",\"qualifiedName\":\"Logger\",\"startLine\":5}]",
    "calls": "[]",
    "heritage": "[{\"childQualifiedName\":\"Greeter\",\"filePath\":\"auth.dart\",\"parentName\":\"Base\",\"relation\":\"EXTENDS\",\"startLine\":17},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"auth.dart\",\"parentName\":\"Logger\",\"relation\":\"IMPLEMENTS\",\"startLine\":17},{\"childQualifiedName\":\"Greeter\",\"filePath\":\"auth.dart\",\"parentName\":\"Timestamps\",\"relation\":\"IMPLEMENTS\",\"startLine\":17}]",
    "imports": "[{\"filePath\":\"auth.dart\",\"kind\":\"namespace\",\"localAlias\":\"meta\",\"source\":\"package:meta/meta.dart\"},{\"filePath\":\"auth.dart\",\"kind\":\"namespace\",\"source\":\"dart:io\"}]"
  },
  "cobol": {
    "definitions": "[]",
    "calls": "[]",
    "heritage": "[]",
    "imports": "[]"
  }
};
