/**
 * Cross-link resolver: pair producers with consumers by exact-match on
 * normalized signatures, augmented by manifest hints.
 *
 * The matcher walks three passes:
 *   1. `signature` — the primary exact-match on `(family, signature)`.
 *      Producers and consumers from different repos with the same
 *      signature pair up.
 *   2. `manifest`  — for each ManifestLink `(producer, consumer, contract)`
 *      we surface a CrossLink when producer-side contracts and
 *      consumer-side contracts exist for the named contract string,
 *      even when signatures don't align exactly.
 *   3. `path`      — deferred. The task lists `path` as a match reason;
 *      our regex-based extractors don't surface path hints today, so this
 *      stays empty for now and is included in the type union for future
 *      detectors.
 *
 * Determinism: contracts and crossLinks are sorted so the generated
 * registry is byte-identical across invocations.
 */

import type { Contract, ContractRegistry, ContractType, CrossLink } from "./types.js";

/** Optional manifest-derived pairing hint. */
export interface ManifestLink {
  readonly producerRepo: string;
  readonly consumerRepo: string;
  readonly contract: string;
  readonly type: ContractType;
}

/** Bucket a contract into the "family" that producers/consumers share. */
export function contractFamily(type: ContractType): "http" | "grpc" | "topic" {
  if (type === "http_route" || type === "http_call") return "http";
  if (type === "grpc_service" || type === "grpc_client") return "grpc";
  return "topic";
}

/** `true` when the contract is on the producer side. */
export function isProducer(type: ContractType): boolean {
  return type === "http_route" || type === "grpc_service" || type === "topic_producer";
}

function compareContracts(a: Contract, b: Contract): number {
  if (a.repo !== b.repo) return a.repo < b.repo ? -1 : 1;
  if (a.type !== b.type) return a.type < b.type ? -1 : 1;
  if (a.signature !== b.signature) return a.signature < b.signature ? -1 : 1;
  if (a.file !== b.file) return a.file < b.file ? -1 : 1;
  if (a.line !== b.line) return a.line - b.line;
  return 0;
}

function compareCrossLinks(a: CrossLink, b: CrossLink): number {
  const p = compareContracts(a.producer, b.producer);
  if (p !== 0) return p;
  const c = compareContracts(a.consumer, b.consumer);
  if (c !== 0) return c;
  if (a.matchReason !== b.matchReason) return a.matchReason < b.matchReason ? -1 : 1;
  return 0;
}

/**
 * Build a ContractRegistry from per-repo contract lists. Cross-links are
 * generated by signature-match (primary) and manifest hints (secondary).
 */
export function buildRegistry(opts: {
  readonly repos: readonly string[];
  readonly contracts: readonly Contract[];
  readonly manifestLinks?: readonly ManifestLink[];
  readonly now?: () => string;
}): ContractRegistry {
  const allContracts = [...opts.contracts].sort(compareContracts);
  const links = resolveCrossLinks(allContracts, opts.manifestLinks ?? []);
  const now = opts.now ? opts.now() : new Date().toISOString();
  return {
    repos: [...opts.repos].sort(),
    contracts: allContracts,
    crossLinks: links,
    computedAt: now,
  };
}

/**
 * Pair contracts by signature across different repos, then annotate with
 * manifest-derived pairings. Identical pairs discovered by both passes
 * keep their `signature` origin (signature wins over manifest).
 */
export function resolveCrossLinks(
  contracts: readonly Contract[],
  manifestLinks: readonly ManifestLink[],
): readonly CrossLink[] {
  const byFamily = new Map<"http" | "grpc" | "topic", Contract[]>();
  for (const c of contracts) {
    const fam = contractFamily(c.type);
    const bucket = byFamily.get(fam);
    if (bucket) {
      bucket.push(c);
    } else {
      byFamily.set(fam, [c]);
    }
  }

  const signatureKey = new Set<string>();
  const out: CrossLink[] = [];

  // Pass 1: signature-match. For gRPC we also allow a substring match
  // because producers commonly carry a fully-qualified signature like
  // `foo.v1.Greeter/SayHello` while TS / Python consumers only reference
  // the short `Greeter` class name. Substring match is only honored for
  // gRPC — HTTP and topic pairs always demand equality.
  for (const [fam, bucket] of byFamily) {
    const producers = bucket.filter((c) => isProducer(c.type));
    const consumers = bucket.filter((c) => !isProducer(c.type));
    for (const p of producers) {
      for (const c of consumers) {
        if (p.repo === c.repo) continue;
        if (!signaturesMatch(fam, p.signature, c.signature)) continue;
        const key = `${p.repo}|${p.file}|${p.line}|${c.repo}|${c.file}|${c.line}`;
        if (signatureKey.has(key)) continue;
        signatureKey.add(key);
        out.push({ producer: p, consumer: c, matchReason: "signature" });
      }
    }
  }

  // Pass 2: manifest hints. We emit a CrossLink for each
  // (producerRepo, consumerRepo, contract) when at least one matching
  // producer and one matching consumer exist in those repos. We use the
  // `contract` string as the effective signature when the repos' contracts
  // don't expose a compatible signature.
  for (const link of manifestLinks) {
    const fam = contractFamily(link.type);
    const bucket = byFamily.get(fam) ?? [];
    const producers = bucket.filter(
      (c) => isProducer(c.type) && c.repo === link.producerRepo && matchesManifest(c, link),
    );
    const consumers = bucket.filter(
      (c) => !isProducer(c.type) && c.repo === link.consumerRepo && matchesManifest(c, link),
    );
    for (const p of producers) {
      for (const c of consumers) {
        const key = `${p.repo}|${p.file}|${p.line}|${c.repo}|${c.file}|${c.line}`;
        if (signatureKey.has(key)) continue;
        signatureKey.add(key);
        out.push({ producer: p, consumer: c, matchReason: "manifest" });
      }
    }
  }

  return out.sort(compareCrossLinks);
}

function signaturesMatch(
  fam: "http" | "grpc" | "topic",
  producer: string,
  consumer: string,
): boolean {
  if (producer === consumer) return true;
  if (fam !== "grpc") return false;
  // gRPC: accept when the consumer's short name appears as a segment of
  // the producer's fully-qualified name (split by `.` and `/`). Prevents
  // accidental matches on short strings.
  if (consumer.length === 0) return false;
  const tokens = producer.split(/[./]/);
  for (const t of tokens) {
    if (t === consumer) return true;
  }
  return false;
}

function matchesManifest(c: Contract, link: ManifestLink): boolean {
  // For gRPC / topic, the manifest contract is the service or topic
  // identifier embedded in the signature; we substring-check so the
  // signature "foo.v1.BarService/DoThing" matches contract "BarService".
  return c.signature === link.contract || c.signature.includes(link.contract);
}
