/**
 * Summarize phase — emit structured LLM summaries for callable symbols.
 *
 * This is the first hop of the SACL-style two-lane retrieval stack. Every
 * Function / Method / Class that the LSP oracle has independently confirmed
 * gets a Zod 4-validated `SymbolSummary` generated by `@opencodehub/summarizer`
 * (Bedrock Haiku 4.5 via Converse + tool_use). The summaries live in a
 * separate `symbol_summaries` storage table; they never participate in the
 * graph edge set.
 *
 * The phase is gated four ways, in strict precedence:
 *   1. `opts.offline === true` → skip with `skippedReason: "offline"`. The
 *      offline invariant is non-negotiable; no summarizer call path may
 *      execute when offline is set.
 *   2. `opts.summaries !== true` → skip with `skippedReason: "not-enabled"`.
 *      The flag defaults off so re-index runs stay free until the operator
 *      explicitly opts in.
 *   3. Trust filter — a symbol is summarized only when at least one edge
 *      incident on it is SCIP-confirmed (confidence 1.0 and
 *      `reason` starts with an {@link SCIP_PROVENANCE_PREFIXES} entry). This
 *      cuts noise from tree-sitter-only resolution where the symbol's
 *      existence is uncertain.
 *   4. Cost cap — `maxSummariesPerRun` bounds how many Bedrock calls we
 *      actually issue. `maxSummariesPerRun = 0` (the default) runs the
 *      phase in dry-run mode: we record how many symbols WOULD have been
 *      summarized, but never contact Bedrock. Session A ships in this
 *      mode so the operator can inspect the counter before spending
 *      anything on Session B.
 *
 * The LSP phases run upstream, so by the time we get here every high-
 * confidence edge carries its `scip:scip-python@…` / `scip:scip-typescript@…`
 * / `scip:scip-go@…` / `scip:rust-analyzer@…` provenance. The trust filter reads that
 * directly off `ctx.graph`.
 *
 * Cache semantics:
 *   - Content hash = sha256 hex of the UTF-8 bytes of the symbol's source
 *     span `[startLine, endLine]`. A whitespace-only edit to a different
 *     symbol leaves the target symbol's hash stable → cache hit.
 *   - The cache key is `(nodeId, contentHash, promptVersion)`. Bumping
 *     `SUMMARIZER_PROMPT_VERSION` invalidates prior rows without deleting
 *     them; multiple prompt versions can coexist during rollout.
 *   - Cache hits are counted but do NOT re-enter the output `rows` array
 *     — the CLI only persists freshly produced rows. The prior row is
 *     already on disk.
 *
 * Provenance:
 *   - The phase never emits graph edges.
 *   - The phase never mutates graph nodes (no summary text stored inline).
 *   - All output is side-channel, keyed by node id.
 */

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { SCIP_PROVENANCE_PREFIXES } from "@opencodehub/core-types";
import type { SymbolSummaryRow } from "@opencodehub/storage";
import {
  DEFAULT_MODEL_ID,
  SUMMARIZER_PROMPT_VERSION,
  type SummarizeInput,
  type SummarizerResult,
} from "@opencodehub/summarizer";
import type { PipelineContext, PipelinePhase } from "../types.js";
import { CONFIDENCE_DEMOTE_PHASE_NAME } from "./confidence-demote.js";

export const SUMMARIZE_PHASE_NAME = "summarize" as const;

const LSP_CONFIDENCE = 1.0;
const SUMMARIZABLE_KINDS: ReadonlySet<string> = new Set(["Function", "Method", "Class"]);

export interface SummarizePhaseOutput {
  /** `true` when the phase actually considered symbols for summarization. */
  readonly enabled: boolean;
  /** Populated when `enabled=false`; a human-readable hint for logs. */
  readonly skippedReason?: string;
  /** Prompt version that gated the cache key for this run. */
  readonly promptVersion: string;
  /** Model id that WOULD (or did) be invoked — resolved for diagnostics. */
  readonly modelId: string;
  /** Symbols walked after kind filtering. */
  readonly considered: number;
  /** Symbols dropped by the LSP trust filter. */
  readonly skippedUnconfirmed: number;
  /** Symbols whose cached summary already covered the content hash. */
  readonly cacheHits: number;
  /**
   * Symbols eligible but dropped by the cost cap (dry-run or when the
   * batch exceeds `maxSummariesPerRun`).
   */
  readonly wouldHaveSummarized: number;
  /** Bedrock calls that returned a validated summary. */
  readonly summarized: number;
  /** Bedrock calls that threw (retry loop exhausted or transport error). */
  readonly failed: number;
  /** Fresh rows the CLI will persist via `store.bulkLoadSymbolSummaries`. */
  readonly rows: readonly SymbolSummaryRow[];
  readonly durationMs: number;
}

/**
 * Shape the phase uses to talk to the summarizer. Narrower than the full
 * Bedrock client so tests can substitute a fake without instantiating
 * `@aws-sdk/client-bedrock-runtime`. The production path wraps
 * {@link summarizeSymbol} against a real `BedrockRuntimeClient`.
 */
export interface SummarizerAdapter {
  summarize(input: SummarizeInput): Promise<SummarizerResult>;
}

export interface SummarizePhaseTestHooks {
  /**
   * Override the summarizer adapter. When provided, the phase uses this
   * instead of instantiating a real Bedrock client. Tests MUST set this
   * so Bedrock is never contacted.
   */
  readonly summarizerFactory?: (opts: { readonly modelId: string }) => SummarizerAdapter;
  /** Override the source-text reader (test-only). */
  readonly sourceReader?: (absPath: string) => string;
  /** Override the clock so `createdAt` is deterministic in tests. */
  readonly now?: () => Date;
}

let testHooks: SummarizePhaseTestHooks | undefined;
export function __setSummarizePhaseTestHooks__(hooks: SummarizePhaseTestHooks | undefined): void {
  testHooks = hooks;
}

export const summarizePhase: PipelinePhase<SummarizePhaseOutput> = {
  name: SUMMARIZE_PHASE_NAME,
  // Depend on confidence-demote so every LSP phase (and the demotion pass)
  // has finished before we inspect edge provenance. The dep graph guarantees
  // all four lsp-* phases ran upstream, so trust filtering sees the final
  // confidence scores.
  deps: [CONFIDENCE_DEMOTE_PHASE_NAME],
  async run(ctx) {
    return runSummarize(ctx);
  },
};

async function runSummarize(ctx: PipelineContext): Promise<SummarizePhaseOutput> {
  const start = Date.now();
  // Accept `summaryModel` via the options bag — the CLI surface threads
  // `--summary-model <id>` through `PipelineOptions.summaryModel`. A string
  // override replaces the compile-time default; anything else falls back to
  // `DEFAULT_MODEL_ID` so production deployments stay pinned.
  const summaryModelOpt = (ctx.options as { readonly summaryModel?: unknown }).summaryModel;
  const modelId =
    typeof summaryModelOpt === "string" && summaryModelOpt.length > 0
      ? summaryModelOpt
      : DEFAULT_MODEL_ID;
  const promptVersion = SUMMARIZER_PROMPT_VERSION;

  // ---- Offline gate (INVARIANT) ----------------------------------------
  if (ctx.options.offline === true) {
    return emptyOutput(start, {
      skippedReason: "offline",
      promptVersion,
      modelId,
    });
  }

  // ---- Feature flag gate -----------------------------------------------
  if (ctx.options.summaries !== true) {
    return emptyOutput(start, {
      skippedReason: "not-enabled",
      promptVersion,
      modelId,
    });
  }

  // ---- Walk candidates --------------------------------------------------
  // Build per-node inbound/outbound incidence sets so we can apply the LSP
  // trust filter in O(|edges| + |nodes|) rather than O(|edges| × |nodes|).
  const lspConfirmedNodes = new Set<string>();
  for (const edge of ctx.graph.edges()) {
    if (edge.confidence < LSP_CONFIDENCE) continue;
    if (!isLspReason(edge.reason)) continue;
    lspConfirmedNodes.add(edge.from as string);
    lspConfirmedNodes.add(edge.to as string);
  }

  let considered = 0;
  let skippedUnconfirmed = 0;

  interface Candidate {
    readonly nodeId: string;
    readonly filePath: string;
    readonly startLine: number;
    readonly endLine: number;
    readonly enclosingClass: string | null;
    readonly docstring: string | null;
  }
  const candidates: Candidate[] = [];

  for (const node of ctx.graph.nodes()) {
    if (!SUMMARIZABLE_KINDS.has(node.kind)) continue;
    considered += 1;
    if (!lspConfirmedNodes.has(node.id as string)) {
      skippedUnconfirmed += 1;
      continue;
    }
    const startLine = (node as { startLine?: number }).startLine;
    const endLine = (node as { endLine?: number }).endLine;
    if (startLine === undefined || endLine === undefined) continue;
    const enclosingClass =
      typeof (node as { enclosingClass?: unknown }).enclosingClass === "string"
        ? ((node as { enclosingClass?: string }).enclosingClass ?? null)
        : null;
    const docstring =
      typeof (node as { description?: unknown }).description === "string"
        ? ((node as { description?: string }).description ?? null)
        : null;
    candidates.push({
      nodeId: node.id as string,
      filePath: node.filePath,
      startLine,
      endLine,
      enclosingClass,
      docstring,
    });
  }
  // Deterministic order: sort by node id so cap truncation picks a stable
  // subset across runs.
  candidates.sort((a, b) => (a.nodeId < b.nodeId ? -1 : a.nodeId > b.nodeId ? 1 : 0));

  // ---- Read source + hash, classify hit vs miss -------------------------
  const readSource = testHooks?.sourceReader ?? defaultSourceReader;
  interface MissEntry {
    readonly candidate: Candidate;
    readonly source: string;
    readonly contentHash: string;
  }
  let cacheHits = 0;
  const misses: MissEntry[] = [];

  // Resolve a cache adapter from the options bag if the CLI attached one.
  // Phases have no direct store handle, so we route cache probes through a
  // narrow hook on `ctx.options`. Production attaches the DuckDB-backed
  // adapter; tests supply an in-memory fake.
  const cacheAdapter = resolveCacheAdapter(ctx);

  for (const c of candidates) {
    const source = safeReadSpan(readSource, ctx.repoPath, c.filePath, c.startLine, c.endLine);
    if (source === undefined) continue;
    const contentHash = sha256Hex(source);
    if (cacheAdapter !== undefined) {
      const hit = await cacheAdapter.lookup(c.nodeId, contentHash, promptVersion);
      if (hit !== undefined) {
        cacheHits += 1;
        continue;
      }
    }
    misses.push({ candidate: c, source, contentHash });
  }

  // ---- Cost cap ---------------------------------------------------------
  const cap = Math.max(0, Math.floor(ctx.options.maxSummariesPerRun ?? 0));
  // When cap === 0 the phase runs in dry-run mode: every miss contributes
  // to wouldHaveSummarized and we skip Bedrock entirely. When cap > 0 we
  // slice the first `cap` misses into the effective batch and count the
  // overflow (if any) as wouldHaveSummarized too.
  const effectiveBatch = cap === 0 ? [] : misses.slice(0, cap);
  const effectiveWouldHave = cap === 0 ? misses.length : misses.length - effectiveBatch.length;

  if (effectiveBatch.length === 0) {
    return {
      enabled: true,
      promptVersion,
      modelId,
      considered,
      skippedUnconfirmed,
      cacheHits,
      wouldHaveSummarized: effectiveWouldHave,
      summarized: 0,
      failed: 0,
      rows: [],
      durationMs: Date.now() - start,
    };
  }

  // ---- Summarize --------------------------------------------------------
  // Instantiating the summarizer resolves the AWS SDK credential chain, which
  // throws `CredentialsProviderError` / `NoCredentialsError` when no creds
  // are configured. Catch that family here so contributors without Bedrock
  // access still get a green analyze — see SUM-S-002 / SUM-UN-001. Any other
  // factory error continues to surface so real bugs don't go silent.
  let summarizer: SummarizerAdapter;
  try {
    summarizer = (testHooks?.summarizerFactory ?? defaultSummarizerFactory)({ modelId });
  } catch (err) {
    if (isMissingCredentialsError(err)) {
      ctx.onProgress?.({
        phase: SUMMARIZE_PHASE_NAME,
        kind: "note",
        message: "summarize: skipped (no AWS credentials)",
      });
      return emptyOutput(start, {
        skippedReason: "no-credentials",
        promptVersion,
        modelId,
      });
    }
    throw err;
  }
  const now = testHooks?.now ?? (() => new Date());
  const rows: SymbolSummaryRow[] = [];
  let summarized = 0;
  let failed = 0;

  for (const [idx, entry] of effectiveBatch.entries()) {
    const input: SummarizeInput = {
      source: entry.source,
      filePath: entry.candidate.filePath,
      lineStart: entry.candidate.startLine,
      lineEnd: entry.candidate.endLine,
      docstring: entry.candidate.docstring,
      enclosingClass: entry.candidate.enclosingClass,
    };
    try {
      const result = await summarizer.summarize(input);
      const summary = result.summary;
      const signatureSummary = buildSignatureSummary(summary);
      const row: SymbolSummaryRow = {
        nodeId: entry.candidate.nodeId,
        contentHash: entry.contentHash,
        promptVersion,
        modelId,
        summaryText: summary.purpose,
        ...(signatureSummary !== undefined ? { signatureSummary } : {}),
        returnsTypeSummary: summary.returns.type_summary,
        createdAt: now().toISOString(),
      };
      rows.push(row);
      summarized += 1;
    } catch (err) {
      // Credential errors can surface on the first Bedrock call rather than
      // at client construction (e.g. SSO profile expired mid-run). Treat
      // the first such error on the first candidate as a soft-fail for the
      // whole phase so we don't waste the batch on a guaranteed-failing
      // credential chain.
      if (idx === 0 && isMissingCredentialsError(err)) {
        ctx.onProgress?.({
          phase: SUMMARIZE_PHASE_NAME,
          kind: "note",
          message: "summarize: skipped (no AWS credentials)",
        });
        return emptyOutput(start, {
          skippedReason: "no-credentials",
          promptVersion,
          modelId,
        });
      }
      failed += 1;
      ctx.onProgress?.({
        phase: SUMMARIZE_PHASE_NAME,
        kind: "warn",
        message: `summarize: ${entry.candidate.nodeId} failed: ${(err as Error).message}`,
      });
    }
  }

  return {
    enabled: true,
    promptVersion,
    modelId,
    considered,
    skippedUnconfirmed,
    cacheHits,
    wouldHaveSummarized: effectiveWouldHave,
    summarized,
    failed,
    rows,
    durationMs: Date.now() - start,
  };
}

// ---- Helpers ------------------------------------------------------------

function emptyOutput(
  start: number,
  partial: { skippedReason: string; promptVersion: string; modelId: string },
): SummarizePhaseOutput {
  return {
    enabled: false,
    skippedReason: partial.skippedReason,
    promptVersion: partial.promptVersion,
    modelId: partial.modelId,
    considered: 0,
    skippedUnconfirmed: 0,
    cacheHits: 0,
    wouldHaveSummarized: 0,
    summarized: 0,
    failed: 0,
    rows: [],
    durationMs: Date.now() - start,
  };
}

function isLspReason(reason: string | undefined): boolean {
  if (reason === undefined) return false;
  for (const prefix of SCIP_PROVENANCE_PREFIXES) {
    if (reason.startsWith(prefix)) return true;
  }
  return false;
}

function sha256Hex(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}

/**
 * Recognize the AWS SDK v3 credential-missing error family. The SDK
 * throws `CredentialsProviderError` (name) / `NoCredentialsError`
 * depending on the provider in the chain, plus pure-string errors from
 * `from*` providers ("Could not load credentials from any providers").
 *
 * We match on a small set of well-known shapes rather than importing
 * `@smithy/types` to keep the phase independent of the SDK's type
 * surface and safe to call with a test fake that merely sets `name`.
 */
function isMissingCredentialsError(err: unknown): boolean {
  if (err === null || err === undefined) return false;
  const errObj = err as { readonly name?: unknown; readonly message?: unknown };
  const name = typeof errObj.name === "string" ? errObj.name : "";
  if (
    name === "CredentialsProviderError" ||
    name === "NoCredentialsError" ||
    name === "ExpiredTokenException"
  ) {
    return true;
  }
  const message = typeof errObj.message === "string" ? errObj.message : "";
  return (
    message.includes("Could not load credentials") ||
    message.includes("credentials is missing") ||
    message.includes("Unable to load credentials") ||
    message.includes("The security token included in the request is expired")
  );
}

function defaultSourceReader(absPath: string): string {
  return readFileSync(absPath, "utf-8");
}

function safeReadSpan(
  reader: (absPath: string) => string,
  repoPath: string,
  filePath: string,
  startLine: number,
  endLine: number,
): string | undefined {
  try {
    const abs = path.isAbsolute(filePath) ? filePath : path.join(repoPath, filePath);
    const all = reader(abs);
    const lines = all.split(/\r?\n/);
    const from = Math.max(0, startLine - 1);
    const to = Math.min(lines.length, endLine);
    if (to <= from) return undefined;
    return lines.slice(from, to).join("\n");
  } catch {
    return undefined;
  }
}

function buildSignatureSummary(summary: {
  readonly inputs: readonly { readonly name: string; readonly type: string }[];
}): string | undefined {
  if (summary.inputs.length === 0) return undefined;
  return summary.inputs.map((i) => `${i.name}: ${i.type}`).join(", ");
}

/**
 * Lightweight cache adapter a caller can plug onto `ctx.options` to let the
 * phase probe existing summaries before emitting work. The `summarize`
 * phase has no direct `IGraphStore` handle — phases are pure over
 * `PipelineContext` — so we expose a narrow hook (`__summaryCache`) the
 * CLI fills before invoking `runIngestion`. Tests plug in a fake
 * adapter; production may or may not depending on how aggressive the
 * operator wants cache hits to be.
 */
export interface SummaryCacheAdapter {
  lookup(
    nodeId: string,
    contentHash: string,
    promptVersion: string,
  ): Promise<SymbolSummaryRow | undefined>;
}

/**
 * Options-bag extension point. Callers attach the cache adapter via a
 * non-enumerable-looking well-known key so existing snapshot tests that
 * assert on option shape don't break.
 */
export const SUMMARY_CACHE_OPTIONS_KEY = "__summaryCache" as const;

function resolveCacheAdapter(ctx: PipelineContext): SummaryCacheAdapter | undefined {
  const opts = ctx.options as unknown as Record<string, unknown>;
  const cache = opts[SUMMARY_CACHE_OPTIONS_KEY];
  if (cache === undefined || cache === null || typeof cache !== "object") return undefined;
  const adapter = cache as SummaryCacheAdapter;
  if (typeof adapter.lookup !== "function") return undefined;
  return adapter;
}

/**
 * Default summarizer factory. Defers importing `@aws-sdk/client-bedrock-runtime`
 * until the phase actually needs to issue a call, so test runs with
 * `maxSummariesPerRun=0` or `summaries=false` never touch the SDK's
 * credential provider chain.
 */
function defaultSummarizerFactory(opts: { readonly modelId: string }): SummarizerAdapter {
  return {
    summarize: async (input) => {
      const [{ BedrockRuntimeClient }, { summarizeSymbol }] = await Promise.all([
        import("@aws-sdk/client-bedrock-runtime"),
        import("@opencodehub/summarizer"),
      ]);
      const client = new BedrockRuntimeClient({});
      return summarizeSymbol(client, input, { modelId: opts.modelId });
    },
  };
}
